GUI/sky background2
AlemSnyder/Fun-Game pull request #46
Opened 2023-04-29 22:21 UTC by AlemSnyder

This renders stars with triangles.

It is much faster than sky background (one).

2023-05-16 18:00 UTC, egelja requested changes
preliminary comments until we format

2023-05-16 18:00 UTC, egelja commented on src/gui/data_structures/screen_data.cpp
> +    std::vector<unsigned short> indices;
FIXED WIDTH

2023-05-27 23:05 UTC, AlemSnyder commented on make_stars.py
I'm not going to get a python formatter for three files

2023-05-27 23:08 UTC, AlemSnyder commented on src/entity/mesh.hpp
> +    VoxelSize object_geometry = voxel_object.get_size();
its not worth it

2023-05-27 23:54 UTC, egelja commented on src/entity/mesh.hpp
> +    VoxelSize object_geometry = voxel_object.get_size();
Yes it is

2023-07-05 16:46 UTC, AlemSnyder commented
Something something look at imgui

2023-07-05 16:46 UTC, closed without merging